
service: big-mouth

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
       restaurants_api:  https://odcddb6cs0.execute-api.eu-west-1.amazonaws.com/dev/restaurants
       cognito_user_pool_id:  eu-west-1_MucMlqr6n
       cognito_client_id: 61s5uk3gbe2gtu66d3sdlhkpvs
  
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: restaurants
  
  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http: 
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:437640264121:userpool/eu-west-1_MucMlqr6n
    environment:
      restaurants_table: restaurants        
  

resources:
   Resources:
     restaurantsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: restaurants
          AttributeDefinitions:
            - AttributeName: name
              AttributeType: S
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
             





